import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'

import React, { useState, useEffect } from "react";

const BaseURL = "http://localhost:3000";



export default function Home() {

  useEffect(() => {

    const eventSource = new EventSource(`${BaseURL}/api/subscribe`);
    eventSource.onmessage = (e) => console.log(e.data);
   
    return () => {
      eventSource.close();
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>hello</h1>
      </main>
    </>
  )
}
